//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using HLP.GeraXml.Comum.Static;
using System;
using System.Data;
using System.Linq;
using System.Xml;
using HLP.GeraXml.WebServiceHomologacao.MDFe_Homologacao_StatusServico;
using HLP.GeraXml.Comum;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

namespace HLP.GeraXml.bel.MDFe
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.portalfiscal.inf.br/mdfe")]
    [System.Xml.Serialization.XmlRootAttribute("consStatServMDFe", Namespace = "http://www.portalfiscal.inf.br/mdfe", IsNullable = false)]
    public partial class TConsStatServ
    {
        private TAmb tpAmbField;
        private string xServField;
        private string versaoField;
        public TConsStatServ()
        {
            this.xServField = "STATUS";
            this.versao = Acesso.versaoMDFe;
            this.tpAmb = Acesso.TP_AMB == 1 ? TAmb.Item1 : TAmb.Item2;

        }
        /// <remarks/>
        public TAmb tpAmb
        {
            get
            {
                return this.tpAmbField;
            }
            set
            {
                this.tpAmbField = value;
            }
        }
        /// <remarks/>
        public string xServ
        {
            get
            {
                return this.xServField;
            }
            set
            {
                this.xServField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }




    }
}