//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17379.
// 
#pragma warning disable 1591

namespace HLP.GeraXml.WebService.Ws_versionamento_Cliente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerisionamentoSoap", Namespace="http://tempuri.org/")]
    public partial class Verisionamento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificaVersaoLiberadaParaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaInforcoesSobreAtualizacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaUltimaVersaoDisponivelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Verisionamento() {
            this.Url = global::HLP.GeraXml.WebService.Properties.Settings.Default.HLP_GeraXml_WebService_Ws_versionamento_Cliente_Verisionamento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificaVersaoLiberadaParaClienteCompletedEventHandler VerificaVersaoLiberadaParaClienteCompleted;
        
        /// <remarks/>
        public event BuscaInforcoesSobreAtualizacaoCompletedEventHandler BuscaInforcoesSobreAtualizacaoCompleted;
        
        /// <remarks/>
        public event BuscaUltimaVersaoDisponivelCompletedEventHandler BuscaUltimaVersaoDisponivelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaVersaoLiberadaParaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificaVersaoLiberadaParaCliente(string sNomeCliente) {
            object[] results = this.Invoke("VerificaVersaoLiberadaParaCliente", new object[] {
                        sNomeCliente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaVersaoLiberadaParaClienteAsync(string sNomeCliente) {
            this.VerificaVersaoLiberadaParaClienteAsync(sNomeCliente, null);
        }
        
        /// <remarks/>
        public void VerificaVersaoLiberadaParaClienteAsync(string sNomeCliente, object userState) {
            if ((this.VerificaVersaoLiberadaParaClienteOperationCompleted == null)) {
                this.VerificaVersaoLiberadaParaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaVersaoLiberadaParaClienteOperationCompleted);
            }
            this.InvokeAsync("VerificaVersaoLiberadaParaCliente", new object[] {
                        sNomeCliente}, this.VerificaVersaoLiberadaParaClienteOperationCompleted, userState);
        }
        
        private void OnVerificaVersaoLiberadaParaClienteOperationCompleted(object arg) {
            if ((this.VerificaVersaoLiberadaParaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaVersaoLiberadaParaClienteCompleted(this, new VerificaVersaoLiberadaParaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaInforcoesSobreAtualizacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscaInforcoesSobreAtualizacao(string sVersao) {
            object[] results = this.Invoke("BuscaInforcoesSobreAtualizacao", new object[] {
                        sVersao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaInforcoesSobreAtualizacaoAsync(string sVersao) {
            this.BuscaInforcoesSobreAtualizacaoAsync(sVersao, null);
        }
        
        /// <remarks/>
        public void BuscaInforcoesSobreAtualizacaoAsync(string sVersao, object userState) {
            if ((this.BuscaInforcoesSobreAtualizacaoOperationCompleted == null)) {
                this.BuscaInforcoesSobreAtualizacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaInforcoesSobreAtualizacaoOperationCompleted);
            }
            this.InvokeAsync("BuscaInforcoesSobreAtualizacao", new object[] {
                        sVersao}, this.BuscaInforcoesSobreAtualizacaoOperationCompleted, userState);
        }
        
        private void OnBuscaInforcoesSobreAtualizacaoOperationCompleted(object arg) {
            if ((this.BuscaInforcoesSobreAtualizacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaInforcoesSobreAtualizacaoCompleted(this, new BuscaInforcoesSobreAtualizacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaUltimaVersaoDisponivel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscaUltimaVersaoDisponivel() {
            object[] results = this.Invoke("BuscaUltimaVersaoDisponivel", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaUltimaVersaoDisponivelAsync() {
            this.BuscaUltimaVersaoDisponivelAsync(null);
        }
        
        /// <remarks/>
        public void BuscaUltimaVersaoDisponivelAsync(object userState) {
            if ((this.BuscaUltimaVersaoDisponivelOperationCompleted == null)) {
                this.BuscaUltimaVersaoDisponivelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaUltimaVersaoDisponivelOperationCompleted);
            }
            this.InvokeAsync("BuscaUltimaVersaoDisponivel", new object[0], this.BuscaUltimaVersaoDisponivelOperationCompleted, userState);
        }
        
        private void OnBuscaUltimaVersaoDisponivelOperationCompleted(object arg) {
            if ((this.BuscaUltimaVersaoDisponivelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaUltimaVersaoDisponivelCompleted(this, new BuscaUltimaVersaoDisponivelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void VerificaVersaoLiberadaParaClienteCompletedEventHandler(object sender, VerificaVersaoLiberadaParaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaVersaoLiberadaParaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaVersaoLiberadaParaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void BuscaInforcoesSobreAtualizacaoCompletedEventHandler(object sender, BuscaInforcoesSobreAtualizacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaInforcoesSobreAtualizacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaInforcoesSobreAtualizacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void BuscaUltimaVersaoDisponivelCompletedEventHandler(object sender, BuscaUltimaVersaoDisponivelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaUltimaVersaoDisponivelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaUltimaVersaoDisponivelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591