//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.GeraXml.WebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteConsulta_CteConsulta {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteConsulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteCancelamento.asmx")]
        public string HLP_GeraXml_WebService_CTe_Homologacao_cteCancelamento_CteCancelamento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Homologacao_cteCancelamento_CteCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx")]
        public string HLP_GeraXml_WebService_CTe_Homologacao_cteConsulta_CteConsulta {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Homologacao_cteConsulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string HLP_GeraXml_WebService_CTe_Homologacao_cteInutilizacao_CteInutilizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Homologacao_cteInutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx")]
        public string HLP_GeraXml_WebService_br_gov_sp_fazenda_nfe_homologacao_CteRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_br_gov_sp_fazenda_nfe_homologacao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx")]
        public string HLP_GeraXml_WebService_CTe_Homologacao_cteRetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Homologacao_cteRetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx")]
        public string HLP_GeraXml_WebService_CTe_Homologacao_cteStatusServico_CteStatusServico {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Homologacao_cteStatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteInutilizacao_CteInutilizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteInutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteRecepcao_CteRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteRecepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteRetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteRetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteStatusServico_CteStatusServico {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteStatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.ginfes.com.br//ServiceGinfesImpl")]
        public string HLP_GeraXml_WebService_Itu_servicos_Homologacao_ServiceGinfesImplService {
            get {
                return ((string)(this["HLP_GeraXml_WebService_Itu_servicos_Homologacao_ServiceGinfesImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.ginfes.com.br//ServiceGinfesImpl")]
        public string HLP_GeraXml_WebService_Itu_servicos_Producao_ServiceGinfesImplService {
            get {
                return ((string)(this["HLP_GeraXml_WebService_Itu_servicos_Producao_ServiceGinfesImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeCancelamento2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_MS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_MS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_RS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_RS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_SP_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeCancelamento_SP_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_MS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_MS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_RS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_RS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_SP_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeConsulta_SP_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeConsultaCadastro_MS_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeConsultaCadastro_MS_CadConsultaCadastro2" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeInutilizacao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeInutilizacao_MS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeInutilizacao_MS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeInutilizacao_RS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeInutilizacao_RS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeInutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_br_gov_sp_fazenda_nfe_homologacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_br_gov_sp_fazenda_nfe_homologacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_MS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_MS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_RS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_RS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_SP_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcao_SP_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcaoEvento_RS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcaoEvento_RS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx" +
            "")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcaoEvento_SP_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRecepcaoEvento_SP_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRetRecepacao_RS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRetRecepacao_RS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeRetRecepcao_MS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeRetRecepcao_MS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeRetRecepcao_SP_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeRetRecepcao_SP_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_MS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_MS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asm" +
            "x")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_RS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_RS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_SP_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NFeStatusServico_SP_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeCancelamento2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_MS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_MS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_RS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_RS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfecancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_SP_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeCancelamento_SP_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeConsulta2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsulta_MS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsulta_MS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsulta_RS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsulta_RS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeconsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsulta_SP_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsulta_SP_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_br_gov_ms_fazenda_nfe_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_br_gov_ms_fazenda_nfe_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sef.sefaz.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_RS_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_RS_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/cadconsultacadastro2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_SP_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_SP_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeInutilizacao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_MS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_MS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_RS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_RS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeinutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_SP_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeInutilizacao_SP_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_MS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_MS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_RS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_RS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_SP_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_SP_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/RecepcaoEvento")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_MS_NfeRecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_MS_NfeRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_RS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_RS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferetrecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_SP_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_SP_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeStatusServico2")]
        public string HLP_GeraXml_WebService_br_gov_ms_fazenda_nfe_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_br_gov_ms_fazenda_nfe_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeStatusServico_RS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeStatusServico_RS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfestatusservico2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeStatusServico_SP_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeStatusServico_SP_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeConsulta_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Homologacao_NFeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeConsulta_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NFeStatusServico2/NFeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_SCAN_Producao_NFeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SCAN_Producao_NFeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.75.170.94/Versionamento/Verisionamento.asmx")]
        public string HLP_GeraXml_WebService_Ws_versionamento_Cliente_Verisionamento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_Ws_versionamento_Cliente_Verisionamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_SP_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcaoEvento_SP_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_SVRS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRecepcao_SVRS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_RetRecepcao_SVRS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_RetRecepcao_SVRS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_Cancelamento_SVRS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_Cancelamento_SVRS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_Inutilizacao_SVRS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_Inutilizacao_SVRS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_Consulta_SVRS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_Consulta_SVRS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_StatusServico_SVRS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_StatusServico_SVRS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string HLP_GeraXml_WebService_V2_Producao_RecepcaoEvento_SVRS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Producao_RecepcaoEvento_SVRS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_Recepcao_SVRS_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_Recepcao_SVRS_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2." +
            "asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_RetRecepcao_SVRS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_RetRecepcao_SVRS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento" +
            "2.asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_Cancelamento_SVRS_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_Cancelamento_SVRS_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao" +
            "2.asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_Inutilizacao_SVRS_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_Inutilizacao_SVRS_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_Consulta_SVRS_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_Consulta_SVRS_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServi" +
            "co2.asmx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_StatusServico_SVRS_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_StatusServico_SVRS_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.a" +
            "smx")]
        public string HLP_GeraXml_WebService_V2_Homologacao_RecepcaoEvento_SVRS_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_V2_Homologacao_RecepcaoEvento_SVRS_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeStatusServico_MG_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeStatusServico_MG_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeRecepcao_MG_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeRecepcao_MG_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeRetRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeRetRecepcao_MG_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeRetRecepcao_MG_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeCancelamento2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeCancelamento_MG_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeCancelamento_MG_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeInutilizacao_MG_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeInutilizacao_MG_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeConsultaProtocolo_MG_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeConsultaProtocolo_MG_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2")]
        public string HLP_GeraXml_WebService_v2_Producao_NfeConsultaCadastro_MG_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NfeConsultaCadastro_MG_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeRecepcao_MG_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeRecepcao_MG_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeRetRecepcao_MG_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeRetRecepcao_MG_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeCancelamento2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeCancelamento_MG_NfeCancelamento2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeCancelamento_MG_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeInutilizacao_MG_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeInutilizacao_MG_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeConsultaProtocolo_MG_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeConsultaProtocolo_MG_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeStatusServico_MG_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeStatusServico_MG_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2")]
        public string HLP_GeraXml_WebService_v2_Homologacao_NfeConsultaCadastro_MG_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_NfeConsultaCadastro_MG_CadConsultaCadastro2" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento")]
        public string HLP_GeraXml_WebService_v2_Producao_RecepcaoEvento_MG_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_RecepcaoEvento_MG_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento")]
        public string HLP_GeraXml_WebService_v2_Homologacao_RecepcaoEvento_MG_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Homologacao_RecepcaoEvento_MG_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.susesu.com.br/wsnfd/serviconfd.asmx")]
        public string HLP_GeraXml_WebService_Susessu_Producao_Servico_ServicoNfd {
            get {
                return ((string)(this["HLP_GeraXml_WebService_Susessu_Producao_Servico_ServicoNfd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pira.comunix.net/gestaopublica/wsnfd/ServicoNfd.asmx")]
        public string HLP_GeraXml_WebService_Susesu_Homologacao_Servico_ServicoNfd {
            get {
                return ((string)(this["HLP_GeraXml_WebService_Susesu_Homologacao_Servico_ServicoNfd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.ms.gov.br/producao/services2/NfeRetRecepcao2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_MS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_MS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://spe.riodasostras.rj.gov.br/nfse/WSNacional/nfse.asmx")]
        public string HLP_GeraXml_WebService_riodasostras_Producao_Nfse {
            get {
                return ((string)(this["HLP_GeraXml_WebService_riodasostras_Producao_Nfse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://issdigital.campinas.sp.gov.br/WsNFe2/LoteRps.jws")]
        public string HLP_GeraXml_WebService_NFSE_Campinas_LoteRpsService {
            get {
                return ((string)(this["HLP_GeraXml_WebService_NFSE_Campinas_LoteRpsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_RS_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeRetRecepcao_RS_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/CteCancelamento.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_cteCancelamento_CteCancelamento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_cteCancelamento_CteCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteweb/services/cteRecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_CTe_Producao_evento_CteRecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_CTe_Producao_evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.sefaz.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx")]
        public string HLP_GeraXml_WebService_MDFe_Producao_Recepcao_MDFeRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_MDFe_Producao_Recepcao_MDFeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.sefaz.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx")]
        public string HLP_GeraXml_WebService_MDFe_Producao_RetRecepcao_MDFeRetRecepcao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_MDFe_Producao_RetRecepcao_MDFeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.sefaz.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_MDFe_Producao_RecepcaoEvento_MDFeRecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_MDFe_Producao_RecepcaoEvento_MDFeRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.sefaz.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx")]
        public string HLP_GeraXml_WebService_MDFe_Producao_Consulta_MDFeConsulta {
            get {
                return ((string)(this["HLP_GeraXml_WebService_MDFe_Producao_Consulta_MDFeConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.sefaz.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx")]
        public string HLP_GeraXml_WebService_MDFe_Producao_StatusServico_MDFeStatusServico {
            get {
                return ((string)(this["HLP_GeraXml_WebService_MDFe_Producao_StatusServico_MDFeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://svp-ws.sefazvirtual.rs.gov.br/ws/CadConsultaCadastro/CadConsultaCadastro2" +
            ".asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_RS1_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_RS1_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_BA_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_BA_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_CE_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_CE_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_br_gov_go_sefaz_nfe_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_br_gov_go_sefaz_nfe_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_MT_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_MT_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.pe.gov.br/nfe-service/services/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_PE_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_PE_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe2.fazenda.pr.gov.br/nfe/CadConsultaCadastro2")]
        public string HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_PR_CadConsultaCadastro2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_Producao_NFeConsultaCadastro_PR_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_AN_HOMOLOGACAO_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_AN_HOMOLOGACAO_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_AN_PRODUCAO_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_AN_PRODUCAO_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_HLP_GeraXml_WebService_v2_SVAN_Producao_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_HLP_GeraXml_WebService_v2_SVAN_Producao_RecepcaoEvento_Rec" +
                    "epcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeConsultaProtocolo_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeConsultaProtocolo_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NfeDownloadNF_NfeDownloadNF {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NfeDownloadNF_NfeDownloadNF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NFeAutorizacao_NfeAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NFeAutorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVAN_Producao_NFeRetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVAN_Producao_NFeRetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NfeConsultaProtocolo_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NfeConsultaProtocolo_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NfeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NfeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NFeAutorizacao_NfeAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NFeAutorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Producao_NFeRetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Producao_NFeRetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeConsultaProtocolo_NfeConsulta2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeConsultaProtocolo_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NfeStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NFeAutorizacao_NfeAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NFeAutorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string HLP_GeraXml_WebService_v2_SVC_Homologacao_NFeRetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["HLP_GeraXml_WebService_v2_SVC_Homologacao_NFeRetAutorizacao_NfeRetAutorizacao"]));
            }
        }
    }
}
