//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using HLP.GeraXml.bel;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.portalfiscal.inf.br/cte", IsNullable = false)]
public partial class evCancCTe
{

    private evCancCTeDescEvento descEventoField;

    private string nProtField;

    private string xJustField;

    /// <remarks/>
    public evCancCTeDescEvento descEvento
    {
        get
        {
            return this.descEventoField;
        }
        set
        {
            this.descEventoField = value;
        }
    }

    /// <remarks/>
    public string nProt
    {
        get
        {
            return this.nProtField;
        }
        set
        {
            this.nProtField = value;
        }
    }

    /// <remarks/>
    public string xJust
    {
        get
        {
            return this.xJustField;
        }
        set
        {
            this.xJustField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
public enum evCancCTeDescEvento
{

    /// <remarks/>
    Cancelamento,
}




