//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.portalfiscal.inf.br/cte", IsNullable = false)]
public partial class evCCeCTe
{

    private evCCeCTeDescEvento descEventoField;

    private List<evCCeCTeInfCorrecao> infCorrecaoField;

    private evCCeCTeXCondUso xCondUsoField;

    /// <remarks/>
    public evCCeCTeDescEvento descEvento
    {
        get
        {
            return this.descEventoField;
        }
        set
        {
            this.descEventoField = value;
        }
    }

    [System.Xml.Serialization.XmlIgnore]
    public string CD_NRLANC { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infCorrecao")]
    public List<evCCeCTeInfCorrecao> infCorrecao
    {
        get
        {
            return this.infCorrecaoField;
        }
        set
        {
            this.infCorrecaoField = value;
        }
    }

    /// <remarks/>
    public evCCeCTeXCondUso xCondUso
    {
        get
        {
            return this.xCondUsoField;
        }
        set
        {
            this.xCondUsoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
public enum evCCeCTeDescEvento
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Carta de Correção")]
    CartadeCorreção,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Carta de Correcao")]
    CartadeCorrecao,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
public partial class evCCeCTeInfCorrecao
{

    private string grupoAlteradoField;

    private string campoAlteradoField;

    private string valorAlteradoField;

    private string nroItemAlteradoField;

    /// <remarks/>
    public string grupoAlterado
    {
        get
        {
            return this.grupoAlteradoField;
        }
        set
        {
            this.grupoAlteradoField = value;
        }
    }

    /// <remarks/>
    public string campoAlterado
    {
        get
        {
            return this.campoAlteradoField;
        }
        set
        {
            this.campoAlteradoField = value;
        }
    }

    /// <remarks/>
    public string valorAlterado
    {
        get
        {
            return this.valorAlteradoField;
        }
        set
        {
            this.valorAlteradoField = value;
        }
    }

    /// <remarks/>
    public string nroItemAlterado
    {
        get
        {
            return this.nroItemAlteradoField;
        }
        set
        {
            this.nroItemAlteradoField = string.IsNullOrEmpty(value) ? null : value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.portalfiscal.inf.br/cte")]
public enum evCCeCTeXCondUso
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(@"A Carta de Correção é disciplinada pelo Art. 58-B do CONVÊNIO/SINIEF 06/89: Fica permitida a utilização de carta de correção, para regularização de erro ocorrido na emissão de documentos fiscais relativos à prestação de serviço de transporte, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da prestação;II - a correção de dados cadastrais que implique mudança do emitente, tomador, remetente ou do destinatário;III - a data de emissão ou de saída.")]
    ACartadeCorreçãoédisciplinadapeloArt58BdoCONVÊNIOSINIEF0689FicapermitidaautilizaçãodecartadecorreçãopararegularizaçãodeerroocorridonaemissãodedocumentosfiscaisrelativosàprestaçãodeserviçodetransportedesdequeoerronãoestejarelacionadocomIasvariáveisquedeterminamovalordoimpostotaiscomobasedecálculoalíquotadiferençadepreçoquantidadevalordaprestaçãoIIacorreçãodedadoscadastraisqueimpliquemudançadoemitentetomadorremetenteoudodestinatárioIIIadatadeemissãooudesaída,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(@"A Carta de Correcao e disciplinada pelo Art. 58-B do CONVENIO/SINIEF 06/89: Fica permitida a utilizacao de carta de correcao, para regularizacao de erro ocorrido na emissao de documentos fiscais relativos a prestacao de servico de transporte, desde que o erro nao esteja relacionado com: I - as variaveis que determinam o valor do imposto tais como: base de calculo, aliquota, diferenca de preco, quantidade, valor da prestacao;II - a correcao de dados cadastrais que implique mudanca do emitente, tomador, remetente ou do destinatario;III - a data de emissao ou de saida.")]
    ACartadeCorrecaoedisciplinadapeloArt58BdoCONVENIOSINIEF0689FicapermitidaautilizacaodecartadecorrecaopararegularizacaodeerroocorridonaemissaodedocumentosfiscaisrelativosaprestacaodeservicodetransportedesdequeoerronaoestejarelacionadocomIasvariaveisquedeterminamovalordoimpostotaiscomobasedecalculoaliquotadiferencadeprecoquantidadevalordaprestacaoIIacorrecaodedadoscadastraisqueimpliquemudancadoemitentetomadorremetenteoudodestinatarioIIIadatadeemissaooudesaida,
}


